{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (not .Values.persistence.csi.inline) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spool-rack.fullname" . }}
  labels:
    {{- include "spool-rack.labels" . | nindent 4 }}
    {{- with .Values.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  volumeMode: {{ .Values.persistence.volumeMode | default "Filesystem" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.csi.enabled }}
  volumeName: {{ include "spool-rack.fullname" . }}-pv
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- else if .Values.persistence.csi.enabled }}
  storageClassName: ""
  {{- end }}
{{- end }}
