apiVersion: v2
name: spool-rack
description: A Helm chart for the Spool Rack server
type: application
version: 0.3.0
appVersion: "0.3.0"
annotations:
  org.opencontainers.image.source: https://github.com/autonomous-bits/spool-rack
  org.opencontainers.image.description: Helm chart for Spool Rack server
  org.opencontainers.image.licenses: AGPL-3.0-only
